"""corrections_log survives assessment deletion

Revision ID: 10ac8cf998e8
Revises: 4c30461fa23a
Create Date: 2026-08-26 07:42:02.105763
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "10ac8cf998e8"
down_revision = "4c30461fa23a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("corrections_log", "assessment_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("corrections_log", "assessment_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
