"""initial schema per PRD section 12

Revision ID: 4c30461fa23a
Revises:
Create Date: 2026-08-26 07:03:25.553793
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "4c30461fa23a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("lms_type", sa.String(), nullable=True),
        sa.Column("default_due_time", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("subject_code", sa.String(), nullable=False),
        sa.Column("catalog_number", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("credits", sa.Float(), nullable=False),
        sa.Column("gened_attributes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "institution_id", "subject_code", "catalog_number", name="uq_course_code"
        ),
    )
    op.create_index(op.f("ix_courses_institution_id"), "courses", ["institution_id"], unique=False)
    op.create_table(
        "instructors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("canonical_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instructors_canonical_name"), "instructors", ["canonical_name"], unique=False
    )
    op.create_index(
        op.f("ix_instructors_institution_id"), "instructors", ["institution_id"], unique=False
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("add_drop_date", sa.Date(), nullable=True),
        sa.Column("withdrawal_date", sa.Date(), nullable=True),
        sa.Column("finals_start", sa.Date(), nullable=True),
        sa.Column("finals_end", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_terms_institution_id"), "terms", ["institution_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("calibration_factor", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_institution_id"), "users", ["institution_id"], unique=False)
    op.create_table(
        "calendar_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("target_calendar_id", sa.String(), nullable=True),
        sa.Column("sync_token", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_connections_user_id"), "calendar_connections", ["user_id"], unique=False
    )
    op.create_table(
        "calendar_exceptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("no_class", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_exceptions_term_id"), "calendar_exceptions", ["term_id"], unique=False
    )
    op.create_table(
        "course_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("instructor_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assessment_mix", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("est_weekly_hours", sa.Float(), nullable=True),
        sa.Column("has_group_project", sa.Boolean(), nullable=True),
        sa.Column("attendance_graded", sa.Boolean(), nullable=True),
        sa.Column("exam_count", sa.Integer(), nullable=True),
        sa.Column("final_exam_type", sa.String(), nullable=True),
        sa.Column("graded_item_count", sa.Integer(), nullable=True),
        sa.Column("est_materials_cost_usd", sa.Float(), nullable=True),
        sa.Column("source_document_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("verification_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "instructor_id", "term_id", name="uq_course_profile"),
    )
    op.create_index(
        op.f("ix_course_profiles_course_id"), "course_profiles", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_profiles_instructor_id"), "course_profiles", ["instructor_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_profiles_term_id"), "course_profiles", ["term_id"], unique=False
    )
    op.create_table(
        "final_exam_matrix",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("meeting_pattern", sa.String(), nullable=False),
        sa.Column("exam_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exam_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_final_exam_matrix_term_id"), "final_exam_matrix", ["term_id"], unique=False
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("section_code", sa.String(), nullable=False),
        sa.Column("instructor_id", sa.UUID(), nullable=True),
        sa.Column("meeting_pattern", sa.String(), nullable=True),
        sa.Column("modality", sa.String(), nullable=True),
        sa.Column("seats_total", sa.Integer(), nullable=True),
        sa.Column("seats_open", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sections_course_id"), "sections", ["course_id"], unique=False)
    op.create_index(op.f("ix_sections_term_id"), "sections", ["term_id"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "section_id", name="uq_enrollment"),
    )
    op.create_index(op.f("ix_enrollments_section_id"), "enrollments", ["section_id"], unique=False)
    op.create_index(op.f("ix_enrollments_term_id"), "enrollments", ["term_id"], unique=False)
    op.create_index(op.f("ix_enrollments_user_id"), "enrollments", ["user_id"], unique=False)
    op.create_table(
        "section_policies",
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("attendance_graded", sa.Boolean(), nullable=True),
        sa.Column("attendance_weight_pct", sa.Float(), nullable=True),
        sa.Column("late_policy_class", sa.String(), nullable=False),
        sa.Column("group_work_present", sa.Boolean(), nullable=True),
        sa.Column("group_work_weight_pct", sa.Float(), nullable=True),
        sa.Column("final_exam_type", sa.String(), nullable=False),
        sa.Column("curve_mentioned", sa.Boolean(), nullable=True),
        sa.Column("participation_weight_pct", sa.Float(), nullable=True),
        sa.Column("ai_policy_class", sa.String(), nullable=False),
        sa.Column("materials", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("est_materials_cost_usd", sa.Float(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("section_id"),
    )
    op.create_table(
        "syllabus_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("uploader_user_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("mime", sa.String(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("is_scanned", sa.Boolean(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("canonical_for_section", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploader_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_syllabus_documents_section_id"), "syllabus_documents", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_syllabus_documents_sha256"), "syllabus_documents", ["sha256"], unique=False
    )
    op.create_index(
        op.f("ix_syllabus_documents_uploader_user_id"),
        "syllabus_documents",
        ["uploader_user_id"],
        unique=False,
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("category_ref", sa.String(), nullable=True),
        sa.Column("weight_pct", sa.Float(), nullable=True),
        sa.Column("date_expression_raw", sa.String(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_precision", sa.String(), nullable=False),
        sa.Column("time_inferred", sa.Boolean(), nullable=False),
        sa.Column("recurrence_rule", sa.String(), nullable=True),
        sa.Column("is_group", sa.Boolean(), nullable=False),
        sa.Column("effort_hours", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("page_ref", sa.Integer(), nullable=True),
        sa.Column("source_span", sa.Text(), nullable=False),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["syllabus_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_document_id"), "assessments", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_assessments_section_id"), "assessments", ["section_id"], unique=False)
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("pass", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("cost_cents", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["syllabus_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_runs_document_id"), "extraction_runs", ["document_id"], unique=False
    )
    op.create_table(
        "grade_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight_pct", sa.Float(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=True),
        sa.Column("drop_lowest", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["syllabus_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grade_categories_document_id"), "grade_categories", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_grade_categories_section_id"), "grade_categories", ["section_id"], unique=False
    )
    op.create_table(
        "calendar_event_map",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("external_event_id", sa.String(), nullable=False),
        sa.Column("etag", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["calendar_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "assessment_id", name="uq_calendar_event_map"),
    )
    op.create_index(
        op.f("ix_calendar_event_map_assessment_id"),
        "calendar_event_map",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_event_map_connection_id"),
        "calendar_event_map",
        ["connection_id"],
        unique=False,
    )
    op.create_table(
        "corrections_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("source_span", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corrections_log_assessment_id"), "corrections_log", ["assessment_id"], unique=False
    )
    op.create_index(
        op.f("ix_corrections_log_user_id"), "corrections_log", ["user_id"], unique=False
    )
    op.create_table(
        "user_overrides",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effort_hours", sa.Float(), nullable=True),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "assessment_id", name="uq_user_override"),
    )
    op.create_index(
        op.f("ix_user_overrides_assessment_id"), "user_overrides", ["assessment_id"], unique=False
    )
    op.create_index(op.f("ix_user_overrides_user_id"), "user_overrides", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_overrides_user_id"), table_name="user_overrides")
    op.drop_index(op.f("ix_user_overrides_assessment_id"), table_name="user_overrides")
    op.drop_table("user_overrides")
    op.drop_index(op.f("ix_corrections_log_user_id"), table_name="corrections_log")
    op.drop_index(op.f("ix_corrections_log_assessment_id"), table_name="corrections_log")
    op.drop_table("corrections_log")
    op.drop_index(op.f("ix_calendar_event_map_connection_id"), table_name="calendar_event_map")
    op.drop_index(op.f("ix_calendar_event_map_assessment_id"), table_name="calendar_event_map")
    op.drop_table("calendar_event_map")
    op.drop_index(op.f("ix_grade_categories_section_id"), table_name="grade_categories")
    op.drop_index(op.f("ix_grade_categories_document_id"), table_name="grade_categories")
    op.drop_table("grade_categories")
    op.drop_index(op.f("ix_extraction_runs_document_id"), table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index(op.f("ix_assessments_section_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_document_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_syllabus_documents_uploader_user_id"), table_name="syllabus_documents")
    op.drop_index(op.f("ix_syllabus_documents_sha256"), table_name="syllabus_documents")
    op.drop_index(op.f("ix_syllabus_documents_section_id"), table_name="syllabus_documents")
    op.drop_table("syllabus_documents")
    op.drop_table("section_policies")
    op.drop_index(op.f("ix_enrollments_user_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_term_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_section_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_sections_term_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_course_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_final_exam_matrix_term_id"), table_name="final_exam_matrix")
    op.drop_table("final_exam_matrix")
    op.drop_index(op.f("ix_course_profiles_term_id"), table_name="course_profiles")
    op.drop_index(op.f("ix_course_profiles_instructor_id"), table_name="course_profiles")
    op.drop_index(op.f("ix_course_profiles_course_id"), table_name="course_profiles")
    op.drop_table("course_profiles")
    op.drop_index(op.f("ix_calendar_exceptions_term_id"), table_name="calendar_exceptions")
    op.drop_table("calendar_exceptions")
    op.drop_index(op.f("ix_calendar_connections_user_id"), table_name="calendar_connections")
    op.drop_table("calendar_connections")
    op.drop_index(op.f("ix_users_institution_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_terms_institution_id"), table_name="terms")
    op.drop_table("terms")
    op.drop_index(op.f("ix_instructors_institution_id"), table_name="instructors")
    op.drop_index(op.f("ix_instructors_canonical_name"), table_name="instructors")
    op.drop_table("instructors")
    op.drop_index(op.f("ix_courses_institution_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_table("institutions")
    # ### end Alembic commands ###
