"""corrections_log survives account deletion

Revision ID: b65eaafbeb52
Revises: 10ac8cf998e8
Create Date: 2026-08-26 11:41:35.955956
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "b65eaafbeb52"
down_revision = "10ac8cf998e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("corrections_log", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("corrections_log", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
