"""Encryption at rest for OAuth refresh tokens (PRD section 13).

A refresh token is a long-lived credential to a student's calendar. Losing the
database should not mean losing those, which rules out storing them in the
clear, and it rules out a key that lives next to the ciphertext.

Fernet (AES-128-CBC with an HMAC) with a key from Secret Manager. The key is
generated by Terraform and never passes through a human, the same as the JWT
signing key. Encryption happens here rather than in the database so a read
replica, a backup, or a `SELECT *` in a support session never sees a usable
token.

Two deliberate limits:

  - No key rotation yet. Fernet supports it through `MultiFernet`, and the
    ciphertext carries a version byte, so adding it later does not require
    re-encrypting anything. It is not built until there is a reason to rotate.
  - Local development derives a key from JWT_SECRET so that `.env.example`
    works unchanged. Outside local, a missing key is a hard error: silently
    falling back to a derived key in production would defeat the point.
"""

from __future__ import annotations

import base64
import hashlib
import os

from cryptography.fernet import Fernet, InvalidToken


class TokenVaultError(RuntimeError):
    """The vault cannot be used as configured."""


def _key() -> bytes:
    configured = os.environ.get("TOKEN_ENCRYPTION_KEY", "").strip()
    if configured:
        # Fernet wants 32 bytes as url-safe base64. Terraform's random_bytes
        # emits standard base64, and the two alphabets differ in exactly two
        # characters, so accept either rather than fail on a `+`.
        return configured.encode().translate(bytes.maketrans(b"+/", b"-_"))

    if os.environ.get("ENVIRONMENT", "local") == "local":
        seed = os.environ.get("JWT_SECRET", "local-dev-secret-not-for-production")
        return base64.urlsafe_b64encode(hashlib.sha256(seed.encode()).digest())

    raise TokenVaultError(
        "TOKEN_ENCRYPTION_KEY is not set. Refusing to store a calendar refresh "
        "token without encryption outside local development."
    )


def _fernet() -> Fernet:
    try:
        return Fernet(_key())
    except ValueError as exc:
        raise TokenVaultError(f"TOKEN_ENCRYPTION_KEY is not a valid Fernet key: {exc}") from exc


def seal(plaintext: str) -> str:
    """Encrypt for storage. Output is ASCII and safe in a text column."""
    return _fernet().encrypt(plaintext.encode()).decode()


def open_sealed(ciphertext: str) -> str:
    """Decrypt a value produced by `seal`.

    A value that does not decrypt is treated as absent rather than as an
    exception to propagate: the caller's recovery is the same in both cases,
    which is to ask the student to reconnect their calendar.
    """
    try:
        return _fernet().decrypt(ciphertext.encode()).decode()
    except InvalidToken as exc:
        raise TokenVaultError(
            "Stored refresh token could not be decrypted. The encryption key has "
            "changed or the value was written unencrypted; the student needs to "
            "reconnect their calendar."
        ) from exc
