output "api_url" {
  description = "Cloud Run service URL, before the Cloudflare CNAME."
  value       = google_cloud_run_v2_service.api.uri
}

output "app_url" {
  value = "https://api.${var.app_domain}"
}

output "r2_bucket" {
  value = cloudflare_r2_bucket.syllabi.name
}

output "worker_vm_ip" {
  description = "Always-on VM running Redis, Celery, MLflow, and Airflow (18.2)."
  value       = google_compute_instance.worker.network_interface[0].access_config[0].nat_ip
}

output "database_host" {
  description = "Neon endpoint. The connection string itself stays in Secret Manager."
  value       = neon_project.main.database_host
  sensitive   = true
}

output "estimated_monthly_cost_usd" {
  description = <<-EOT
    Section 18.5 costs a four-month term at roughly 50 to 105 dollars for about
    500 students. Infrastructure is the small half: everything except the VM
    and email sits in a free tier, and LLM tokens dominate the rest.
  EOT
  value       = "VM ~$6-10; Cloud Run, Neon, R2, Cloudflare within free tiers; LLM tokens $25-50/term"
}

# ------------------------------------------------------- values CI needs

# These five are what the deploy workflow reads. They are outputs rather than
# something written down in a runbook because every one of them is generated by
# an apply, and a hand-copied resource name that drifts fails a deploy with an
# unhelpful 403.

output "artifact_registry" {
  description = "Image prefix. Tag with the commit SHA, never with latest."
  value       = "${var.gcp_region}-docker.pkg.dev/${var.gcp_project_id}/${google_artifact_registry_repository.images.repository_id}"
}

output "deploy_service_account" {
  description = "Set as GCP_SERVICE_ACCOUNT in GitHub. Impersonated, never keyed."
  value       = google_service_account.deployer.email
}

output "workload_identity_provider" {
  description = "Set as GCP_WORKLOAD_IDENTITY_PROVIDER in GitHub."
  value       = google_iam_workload_identity_pool_provider.github.name
}

output "migrate_job" {
  description = "Cloud Run job the deploy executes before routing traffic."
  value       = google_cloud_run_v2_job.migrate.name
}

output "pages_project" {
  description = "Cloudflare Pages project wrangler deploys the built app to."
  value       = cloudflare_pages_project.web.name
}

output "web_config_json" {
  description = <<-EOT
    Exactly what belongs in the deployed app's config.json. Emitted here so the
    origin the browser calls and the origin CORS allows come from one place; if
    they disagree the app fails only in a real browser, which is the last place
    anyone looks.
  EOT
  value       = jsonencode({ apiBase = "https://api.${var.app_domain}/api/v1", environment = var.environment })
}
