output "api_url" {
  description = "Cloud Run service URL, before the Cloudflare CNAME."
  value       = google_cloud_run_v2_service.api.uri
}

output "app_url" {
  value = "https://api.${var.app_domain}"
}

output "r2_bucket" {
  value = cloudflare_r2_bucket.syllabi.name
}

output "cluster_name" {
  description = "GKE cluster running Redis, Celery, MLflow, and Airflow (18.2)."
  value       = google_container_cluster.main.name
}

output "cluster_location" {
  value = google_container_cluster.main.location
}

output "redis_internal_ip" {
  description = "Reserved address the Redis Service must bind, and the one Cloud Run dials."
  value       = google_compute_address.redis.address
}

output "workload_service_account" {
  description = "Pods impersonate this through Workload Identity to read Secret Manager."
  value       = google_service_account.workload.email
}

output "database_host" {
  description = "Neon endpoint. The connection string itself stays in Secret Manager."
  value       = neon_project.main.database_host
  sensitive   = true
}

output "estimated_monthly_cost_usd" {
  description = <<-EOT
    Section 18.5 costs a four-month term at roughly 50 to 105 dollars for about
    500 students. Infrastructure is the small half: everything except the
    cluster's node pool and email sits in a free tier, and LLM tokens dominate
    the rest. The GKE control plane is covered by the one-zonal-cluster credit,
    so the node pool is the same machine the VM was, at the same price.
  EOT
  value       = "Node pool ~$6-10; GKE control plane, Cloud Run, Neon, R2, Cloudflare within free tiers; LLM tokens $25-50/term"
}

# ------------------------------------------------------- values CI needs

# These five are what the deploy workflow reads. They are outputs rather than
# something written down in a runbook because every one of them is generated by
# an apply, and a hand-copied resource name that drifts fails a deploy with an
# unhelpful 403.

output "artifact_registry" {
  description = "Image prefix. Tag with the commit SHA, never with latest."
  value       = "${var.gcp_region}-docker.pkg.dev/${var.gcp_project_id}/${google_artifact_registry_repository.images.repository_id}"
}

output "deploy_service_account" {
  description = "Set as GCP_SERVICE_ACCOUNT in GitHub. Impersonated, never keyed."
  value       = google_service_account.deployer.email
}

output "workload_identity_provider" {
  description = "Set as GCP_WORKLOAD_IDENTITY_PROVIDER in GitHub."
  value       = google_iam_workload_identity_pool_provider.github.name
}

output "migrate_job" {
  description = "Cloud Run job the deploy executes before routing traffic."
  value       = google_cloud_run_v2_job.migrate.name
}

output "pages_project" {
  description = "Cloudflare Pages project wrangler deploys the built app to."
  value       = cloudflare_pages_project.web.name
}

output "web_config_json" {
  description = <<-EOT
    Exactly what belongs in the deployed app's config.json. Emitted here so the
    origin the browser calls and the origin CORS allows come from one place; if
    they disagree the app fails only in a real browser, which is the last place
    anyone looks.
  EOT
  value       = jsonencode({ apiBase = "https://api.${var.app_domain}/api/v1", environment = var.environment })
}
